returnSubjectName = """ SELECT url FROM questionpaper WHERE subjectname = %s ; """
returnShortForm = """ SELECT url FROM questionpaper WHERE shortform = %s ; """
returnStaff = """ SELECT url FROM questionpaper WHERE staff = %s ; """
# insertIntoTable= """INSERT INTO questionPapers(CODE,NAME,YEAR,URL) VALUES(%s,%s,%s,%s);"""
# updateTable= """UPDATE questionPapers SET CODE=%s WHERE CODE=%s;"""
# deleteTable= """DELETE FROM questionPapers WHERE CODE='{0}';"""